[package]
name = "syncbackup"
version = "0.1.0"
authors = ["hubert <hubert.b.laganiere@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.15"
strum_macros = "0.15"